bindata/assets/secondary-scheduler/deployment.yaml
The kube-scheduler-operator is already handling the verbosiness
setting if the `logLevel` value is given in the SecondaryScheduler
object, like in this snippet:
```yaml
apiVersion: operator.openshift.io/v1
kind: SecondaryScheduler
metadata:
name: secondary-scheduler
namespace: openshift-secondary-scheduler-operator
spec:
managementState: Managed
logLevel: Trace
schedulerConfig: topo-aware-scheduler-config
imageSpec: quay.io/openshift-kni/scheduler-plugin:latest
```
This means that the `-v` setting in the embedded deployment.yaml
is redundant, because another `-v` setting is always going to be
appended.
Signed-off-by: Francesco Romani <fromani@redhat.com>
=> assets: remove redundant -v from deployment

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Following explanation in https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/
=> bug 2057387: CSV: comment out skipRange as there's no previous version to be installed

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
The name needs to by identical as the CRD name itself: https://github.com/openshift/secondary-scheduler-operator/blob/master/manifests/secondary-scheduler-operator.crd.yaml#L4
=> bug 2057358: Fix the CRD name

pkg/operator/operatorclient/interfaces.go
By default operator creates a CR called "cluster". E.g.
```
$ oc get kubescheduler
NAME      AGE
cluster   3h40m
$ oc get kubeapiserver
NAME      AGE
cluster   3h40m
$ oc get kubecontrollermanager
NAME      AGE
cluster   3h40m
```
=> bug 2058692: Expect the SecondarySchedulers CR to be named as 'cluster'

README.md, bindata/assets/secondary-scheduler/clusterrolebinding-system-kube-scheduler.yaml, bindata/assets/secondary-scheduler/clusterrolebinding-system-volume-scheduler.yaml, manifests/volume-scheduler-cluster-role-binding.yaml, pkg/operator/target_config_reconciler.go
To address:
```
E0305 09:43:56.343926       1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StorageClass: unknown (get storageclasses.storage.k8s.io)
```
The system:kube-scheduler does not provide RBAC for
storageclasses.storage.k8s.io resource.
The RBAC is provided by system:volume-scheduler.
=> bug 2043153: Bind system:volume-scheduler to secondary-scheduler SA

bindata/assets/secondary-scheduler/deployment.yaml
This environment variable allows all scheduler plugins to enable OpenShift authentication to Prometheus metrics.
Trimaran plugins particularly used load-watcher libaries to fetch prometheus metrics, which in OpenShift would need a different authentication method than in k8s. It is supported here: https://github.com/paypal/load-watcher/pull/49
=> Enable OpenShift Authentication for scheduler plugins

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
It is possible one of replaces/skips/skipRange is required
to enable update path between releases.
Also see
https://olm.operatorframework.io/docs/concepts/olm-architecture/operator-catalog/creating-an-update-graph/#cross-channel-updates.
=> bug 2102344: Set olm.skipRange to enable update path

Dockerfile, Dockerfile.metadata, Dockerfile.rhel7
4.12 is built with golang v1.18
=> Dockerfile: bump golang version to 1.18

pkg/operator/target_config_reconciler.go
=> Get secondary scheduler cm name from the configuration

deploy/02_clusterrole.yaml, deploy/04_kube-scheduler-cluster-role-binding.yaml, deploy/04_volume-scheduler-cluster-role-binding.yaml, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go
Fixes: https://github.com/openshift/secondary-scheduler-operator/issues/74
=> Reuse existing informer factory for namespaces when listing a config map

test/e2e/bindata/assets/02_serviceaccount.yaml, test/e2e/bindata/assets/03_clusterrole.yaml, test/e2e/bindata/assets/04_clusterrolebinding.yaml, test/e2e/bindata/assets/04_kube-scheduler-cluster-role-binding.yaml, test/e2e/bindata/assets/04_volume-scheduler-cluster-role-binding.yaml, test/e2e/bindata/assets/05_deployment.yaml, test/e2e/operator_test.go
Deploy the secondary scheduler operator from a PR built image.
This way any change made to the operator gets tested as part of a PR.
Note: `IMAGE_FORMAT` env is deprecated. Once the env is gone it can be replaced by `RELEASE_IMAGE_LATEST` which contains the registry as well.
=> WRKLDS-650: e2e: deploy the operator from the pipeline built image

README.md, cmd/secondary-scheduler-operator/main.go, manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml, pkg/operator/starter.go, pkg/operator/target_config_reconciler.go
Keeping the release-4.14 in sync with master:HEAD before we start rebasing to k8s 1.28. After 1.2.0 is out release-4.14 will no longer accept any changes unless decided otherwise.
=> Sync with 4.15

bindata/assets/secondary-scheduler/deployment.yaml
Aligned with https://github.com/openshift/cluster-kube-scheduler-operator/blob/ff72afc0cc93006c6d647919873bbec1740110f0/bindata/assets/kube-scheduler/pod.yaml#L43-L46
=> OCPBUGS-23328: Align resource limits and requests with the default kube-scheduler

deploy/02_clusterrole.yaml, manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
this is used by library-go `ControllerBuilder.Run` to discover cluster topology and setup leader election based on that.
--
There isn't a lot of use in this for this operator as I doubt SNO clusters will be using the secondary scheduler 🤔 
Regardless, this PR should silent the warn seen in the logs.
=> OCPBUGS-28584: deploy: add get/list/watch permissions to infrastructure object

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Backporting https://github.com/openshift/secondary-scheduler-operator/pull/120 to 4.15
=> NO-JIRA: csv: fix the operator name schema

Dockerfile.metadata, Dockerfile.rhel7, deploy/05_deployment.yaml, manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml, test/e2e/bindata/assets/05_deployment.yaml
readOnlyRootFilesystem SecurityContext is enabled by default in Deployment object definition. As a result, /tmp is read-only and not writable.
=> Operator deployment: set an emptyDir /tmp

Dockerfile.metadata, deploy/05_deployment.yaml, manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml, test/e2e/bindata/assets/05_deployment.yaml
readOnlyRootFilesystem SecurityContext is enabled by default in Deployment object definition. As a result, /tmp is read-only and not writable.
=> NO-JIRA: Operator deployment: set an emptyDir /tmp

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
The first time we use a buffer for skipped releases to maintain a reachable to-be-added-patch-releases in the future so `opm index add` is happy to accept the patch releases for all existing index bundle images.
=> WRKLDS-1393: CSV: set skips to allow to add patch releases into all supported bundle index images

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
The first time we use a buffer for skipped releases to maintain a reachable to-be-added-patch-releases in the future so `opm index add` is happy to accept the patch releases for all existing index bundle images.
=> WRKLDS-1231: CSV: set skips to allow to add patch releases into all supported bundle index images

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
We need to skip all supported versions to maintain the upgrade path.
=> WRKLDS-1231: csv: skip all supported versions

bindata/assets/secondary-scheduler/deployment.yaml
Fixes an issue with /bin/kube-scheduler path and scheduler-plugins image
=> OCPBUGS-38317: scheduler-plugins change causes CrashLoopBackOff

deploy/05_deployment.yaml, manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml, test/e2e/bindata/assets/05_deployment.yaml
readOnlyRootFilesystem SecurityContext is enabled by default in Deployment object definition. As a result, /tmp is read-only and not writable.
=> OCPBUGS-44204: Operator deployment: set an emptyDir /tmp

manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Add a few annotations:
- operatorframework.io/cluster-monitoring: "true"
- operatorframework.io/suggested-namespace: "openshift-kube-descheduler-operator"
- console.openshift.io/operator-monitoring-default: "true" to simplify the deployment via OCP console.
=> no-jira: Set suggested-namespace and related annotations

pkg/operator/target_config_reconciler.go
I am using this code as a template for KueueOperator.
As I was reading this code, I noticed that we don't actually use this function in the code.
This seems like a bug to me?
Bringing up the PR as a discussion point to better understand how changing the configmap will actually trigger a new configmap sync?
=> drop unusued functions
