openshift/secondary-scheduler-operator

- Dockerfile
- Makefile
- README.md
- bindata/assets.go
- bindata/assets/secondary-scheduler/clusterrolebinding.yaml
- bindata/assets/secondary-scheduler/deployment.yaml
- bindata/assets/secondary-scheduler/serviceaccount.yaml
- deploy/02_clusterrole.yaml
- deploy/03_clusterrolebinding.yaml
- hack/trimaran-example.sh
The initial commit missed the bindata assets.
And the dockerfile registry images' URLs are outdated.
> Added bindata and updated Dockerfile registry image

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> Copy paste rbac rules from deploy/02_clusterrole.yaml

- Dockerfile
- deploy/00_secondary-scheduler-operator.crd.yaml
- deploy/02_clusterrole.yaml
- deploy/03_clusterrolebinding.yaml
- deploy/05_deployment.yaml
- deploy/07_secondary-scheduler-operator.cr.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
- manifests/secondary-scheduler-operator.crd.yaml
- pkg/apis/secondaryscheduler/v1/types.go
- regenerate CRD to include the `imageSpec` field,
- update deploy manifests (rbac version, setting `imageSpec` field, removing unused IMAGE env)
- sync Dockerfile with Dockerfile.rhel7
> Regenerate CRD, update deploy manifests, sync Dockerfile

- pkg/apis/secondaryscheduler/v1/types.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
To react on changes in the CM KubeSchedulerConfiguration
> Register event handler for namespaced CMs

- Dockerfile
> Dockerfile: bump the go version to 1.17

- Makefile
- test/e2e/bindata/assets.go
- test/e2e/bindata/assets/00_secondary-scheduler-operator.crd.yaml
- test/e2e/bindata/assets/01_namespace.yaml
- test/e2e/bindata/assets/06_configmap.yaml
- test/e2e/bindata/assets/07_secondary-scheduler-operator.cr.yaml
- test/e2e/operator_test.go
> e2e: deploy SSO in the CI cluster

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> CSV: mention schedulerConfig field

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> CSV: add subscription

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> CSV: update the display name

- README.md
> README: link the scheduling framework

- README.md
> Rebuild testing PR

- bindata/assets/secondary-scheduler/deployment.yaml
- deploy/02_clusterrole.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
- pkg/operator/operatorclient/interfaces.go
- pkg/operator/target_config_reconciler.go
- test/e2e/operator_test.go
- rename deployment cluster -> secondary scheduler
- quote ENABLE_OPENSHIFT_AUTH env value
- reduce operator RBAC to minimum
> bug 2072154: Rename deployment to secondary scheduler

- README.md
> Update README instruction on installing catalogsource

- README.md
> bug 2096470: Update README instruction on installing catalogsource to trigger a new cachito entry for a new Brew build

- README.md
> bug 2096470: Update README to trigger a new cachito entry for a new Brew build

- pkg/operator/target_config_reconciler.go
Re-deployment is required when the operator is updated from 1.0.* to 1.1.* in order to apply the pod level security restrictions.
> bug 2105399: Force re-deployment when securitycontext fields are different

- README.md
> No-op change to trigger CPaaS mid-stream changes

- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
- test/e2e/operator_test.go
Same as https://github.com/openshift/cluster-kube-descheduler-operator/pull/272
> use ApplyDeployment instead of ApplyDeploymentWithForce

- .ci-operator.yaml
- pkg/dependencymagnet/dependencymagnet.go
- pkg/generated/clientset/versioned/fake/register.go
- pkg/generated/clientset/versioned/scheme/register.go
> Update the .ci-operator.yaml base image

- OWNERS
- README.md
> Update component + readme built index image from bundle

- README.md
> README.md: bump kube-scheduler image version

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> CSV: set minKubeVersion to 1.26.0

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
Following https://docs.engineering.redhat.com/display/CFC/Best_Practices#Best_Practices-SkipRange
> Set .spec.replaces to avoid removing published/released versions

- cmd/secondary-scheduler-operator/main.go
- pkg/operator/starter.go
- pkg/operator/target_config_reconciler.go
> Address sast scan results

- README.md
> Extend the releases with 1.1.2 and 1.2.0

- README.md
> No-op to retrigger cpass build

- README.md
> Update release matrix

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> NO-JIRA: csv: fix the operator name schema

- Makefile
> OCPBUGS-25130: Makefile: add strictfipsruntime build tag

- OWNERS
> NO-JIRA: update OWNERS

- README.md
> NO-JIRA: readme: update releases

- .snyk
> NO-JIRA: Add .snyk file to exclude vendor and ignore unit tests

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> WRKLDS-1037: csv: fix annotation

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> no-jira: csv: set infra annotations

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> WRKLDS-1270: CSV: claim features.operators.openshift.io/disconnected as true

- Dockerfile.rhel7
> Bump go and ocp versions in dockerfile

- bindata/assets/secondary-scheduler/deployment.yaml
- deploy/05_deployment.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> operand: fix containers[].securityContext.readOnlyRootFilesystem field name

- bindata/assets/secondary-scheduler/deployment.yaml
- deploy/05_deployment.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> WRKLDS-1142: operand: fix containers[].securityContext.readOnlyRootFilesystem field name

- deploy/02_clusterrole.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
- test/e2e/bindata/assets/03_clusterrole.yaml
[OCPBUGS-32976](https://issues.redhat.com/browse/OCPBUGS-32976)
> OCPBUGS-32976: Replace wildcards with an explicit list of verbs

- Dockerfile
> Dockerfile for Konflux

- .tekton/secondary-scheduler-operator-pull-request.yaml
- .tekton/secondary-scheduler-operator-push.yaml
To address some security failures
> [tekton]: build source image, hermetic build

- .tekton/secondary-scheduler-operator-pull-request.yaml
- .tekton/secondary-scheduler-operator-push.yaml
> no-jira: Add snyk secret to run sast-snyk-check job

- deploy/05_deployment.yaml
- deploy/06_configmap.yaml
- deploy/07_secondary-scheduler-operator.cr.yaml
> Update dev deploy manifests to render the latest secondary scheduler

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> no-jira: CSV: provide a list of supported architectures

- bundle.Dockerfile
> no-jira: Add bundle dockerfile for the operator

- Dockerfile
> WRKLDS-1470: Dockerfile: bump base image

- .tekton/secondary-scheduler-operator-bundle-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-push.yaml
> WRKLDS-1470: [tekton]: build source image, hermetic build

- bundle.Dockerfile
- hack/replace-image.sh
> WRKLDS-1470: [bundle]: test component nudging

- .tekton/secondary-scheduler-operator-pull-request.yaml
- .tekton/secondary-scheduler-operator-push.yaml
> WRKLDS-1470: [tekton]: build source image, hermetic builds, extend the list of archs

- bundle.Dockerfile
> WRKLDS-1470: bundle.Dockerfile: point operator image to registry.redhat.io

- bundle.Dockerfile
> [bundle.Dockerfile]: set FROM to a pipiline test accepted base image

- .tekton/secondary-scheduler-operator-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-17-push.yaml
> no-jira: [tekton]: build source image, hermetic builds, extend the list of archs

- .tekton/secondary-scheduler-operator-bundle-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-17-push.yaml
> no-jira: [tekton]: build source image, hermetic builds

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> CSV: replace the smallest existing 1.1.z version

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> no-jira: Update CSV replaces to point to an existing release

- bindata/assets/secondary-scheduler/deployment.yaml
- deploy/05_deployment.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> Set readOnlyRootFilesystem to true

- .tekton/secondary-scheduler-operator-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-17-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-17-push.yaml
```
Required task "rpms-signature-scan" is missing
```
> no-jira: Add required rpms-signature-scan task in tekton

- bundle.Dockerfile
> no-jira: Bundle image bump

- .tekton/secondary-scheduler-operator-bundle-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-17-push.yaml
> no-jira: [tekton]: bundle: run prefetch-dependencies

- bundle.Dockerfile
> no-jira: Bundle stage image ref

- test.yaml
> no-jira: Test 4.17

- README.md
> no-jira: no-op: poke cpass

- bindata/assets/secondary-scheduler/deployment.yaml
- deploy/05_deployment.yaml
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
- test/e2e/bindata/assets/05_deployment.yaml
Backporting https://github.com/openshift/secondary-scheduler-operator/pull/239
> no-jira: Readonlyrootfilesystem

- bundle.Dockerfile
> no-jira: bundle: change the registry prefix to stage

- Dockerfile
> no-jira: Dockerfile: update base image

- test.yaml
> drop test.yaml: operator image nudging is configured

- v4.17/catalog-template.json
- v4.17/catalog/openshift-secondary-scheduler-operator/catalog.json
> no-jira: Update catalog for osso 1.3.2

- .tekton/secondary-scheduler-operator-fbc-4-17-pull-request.yaml
- .tekton/secondary-scheduler-operator-fbc-4-17-push.yaml
> [tekton]: Change build pipeline to use multi-arch matrix builds

- Dockerfile
- bundle.Dockerfile
> no-jira: Dockerfiles for operator and bundle

- hack/replace-image.sh
> no-jira: bundle.Dockerfile: hack/replace-image.sh

- .tekton/secondary-scheduler-operator-4-15-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-15-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-15-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-15-push.yaml
> no-jira: [tekton]: Add snyk secret to run sast-snyk-check job

- .tekton/secondary-scheduler-operator-4-13-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-13-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-13-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-13-push.yaml
> no-jira: Update tekton

- .tekton/secondary-scheduler-operator-4-13-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-13-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-13-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-13-push.yaml
- Dockerfile
> no-jira: Update dockerfile

- bundle.Dockerfile
> no-jira: bundle.Dockerfile: set the right tag for go1.18

- .tekton/secondary-scheduler-operator-bundle-4-15-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-15-push.yaml
> no-jira: Run rpms-signature-scan after build-image-index

- Dockerfile
- README.md
- bundle.Dockerfile
> no-jira: Update dockerfiles

- Dockerfile
> no-jira: Dockerfile: bump(registry.redhat.io/rhel9-4-els/rhel-minimal)

- go.mod
- go.sum
- vendor/golang.org/x/net/http2/client_conn_pool.go
- vendor/golang.org/x/net/http2/config.go
- vendor/golang.org/x/net/http2/config_go124.go
- vendor/golang.org/x/net/http2/config_pre_go124.go
- vendor/golang.org/x/net/http2/frame.go
- vendor/golang.org/x/net/http2/http2.go
- vendor/golang.org/x/net/http2/server.go
- vendor/golang.org/x/net/http2/transport.go
- vendor/golang.org/x/net/http2/unencrypted.go
- vendor/golang.org/x/net/http2/write.go
- vendor/golang.org/x/net/websocket/websocket.go
- vendor/modules.txt
> no-jira: bump(golang.org/x/net)=v0.33.0

- renovate.json
> no-jira: Add renovate.json to limit Konflux PRs

- bundle.Dockerfile
> no-jira: bundle.Dockerfile: pin the operator image

- bundle.Dockerfile
> no-jira: Update bundle.Dockerfile

- bundle.Dockerfile
> no-jira: bundle.Dockerfile: Update secondary-scheduler-rhel9-operator

- v4.18/catalog-template.json
- v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
> Regen catalog for 1.4.0

- v4.18/catalog-template.json
- v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
> Update older images registries and regen catalog

- v4.18/catalog-template.json
- v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
> Update bundle images registries and regen catalog

- bundle.Dockerfile
Non-staging release is not released yet so it can not be pulled.
> no-jira: Experiment: point the bundle.Dockerfile into the staging release

- bundle.Dockerfile
> WRKLDS-1621: bundle.Dockerfile: point the operator image to the latest one

- v4.18/catalog-template.json
- v4.18/catalog/openshift-secondary-scheduler-operator/catalog.json
> WRKLDS-1621: Update bundle image and regen catalog

- renovate.json
> Remove renovate.json as nudging is not postponed, it's dropped

- README.md
> no-jira: update readme releases

- .tekton/secondary-scheduler-operator-4-19-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-19-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-19-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-19-push.yaml
> no-jira: bump(.tekton)=release-4.19

- Dockerfile
- Dockerfile.metadata
- README.md
- bundle.Dockerfile
- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> bump to 1.4.1 release

- .tekton/secondary-scheduler-operator-4-19-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-19-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-19-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-19-push.yaml
> Point tekton jobs to release-4.19 branch

- README.md
> no-op to re-trigger the pipeline

- .tekton/secondary-scheduler-operator-4-19-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-19-push.yaml
> Fix push tekton SA names

- README.md
> no-jira: no-op to re-trigger the pipeline

- .tekton/secondary-scheduler-operator-4-19-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-19-push.yaml
Replacing https://github.com/openshift/secondary-scheduler-operator/pull/459
> no-jira: Update .tekton configs

- bundle.Dockerfile
> no-jira: bundle.Dockerfile: pin to the latest operator image revision

- bundle.Dockerfile
> Bump bundle to the latest operator image reference

- .tekton/secondary-scheduler-operator-4-18-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-18-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-18-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-18-push.yaml
> no-jira: Update the latest tekton changes

- .tekton/secondary-scheduler-operator-4-20-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-20-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-20-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-20-push.yaml
> Bump tekton to 4.20

- manifests/cluster-secondary-scheduler-operator.clusterserviceversion.yaml
> no-jira: csv: Update the list of skipped versions

- .tekton/secondary-scheduler-operator-4-20-pull-request.yaml
- .tekton/secondary-scheduler-operator-4-20-push.yaml
- .tekton/secondary-scheduler-operator-bundle-4-20-pull-request.yaml
- .tekton/secondary-scheduler-operator-bundle-4-20-push.yaml
> .tekton: new task updates require IMAGE_URL and IMAGE_DIGEST envs to be present for apply-tags task

- bundle.Dockerfile
> bundle: pin the operator image to the latest push build

- bindata/assets/secondary-scheduler/deployment.yaml
- pkg/operator/target_config_reconciler.go
> OCPBUGS-58154: secondary-scheduler: Configure tmp volume in case a secondary scheduler framework wants to creat a temp dir/file

- README.md
> no-jira: chore: no-op: re-trigger pipeline

- README.md
> no-jira: chore: re-trigger pipeline

- README.md
> fix(readme): fix mentioned golang version for 1.5.0 release

- README.md
> chore: fix with master branch
